import React, { createContext, useContext, useState } from "react";

export type Language = "zh" | "en";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  zh: {
    // Nav
    "nav.home": "首頁",
    "nav.services": "服務項目",
    "nav.company": "公司簡介",
    "nav.cases": "實績案例",
    "nav.news": "最新消息",
    "nav.careers": "招募公告",
    "nav.contact": "聯絡我們",

    // Common CTA Banner
    "cta.title": "展開您的日本不動產旅程",
    "cta.button": "立即預約諮詢",

    // Footer
    "footer.desc": "立足日本，持有正式宅地建物取引業執照。從買賣仲介、租賃管理、收購再販、土地開發、自地自建到住宿設施營運，提供全方位的不動產實務支持。",
    "footer.nav": "網站導覽",
    "footer.careers": "職涯發展",
    "footer.location": "公司所在地",
    "footer.opps": "工作機會",
    "footer.culture": "企業文化",
    "footer.contact_hr": "聯絡我們",
    "footer.copyright": "© 2026 株式会社イエローハウスカンパニー (YELLOW HOUSE COMPANY). ALL RIGHTS RESERVED.",
    "footer.privacy": "隱私權政策",
    "footer.terms": "服務條款",
    "footer.map_label": "神奈川 本社",

    // Home
    "home.title": "Yellow House - 日本在地的實務不動產夥伴 | 株式会社イエローハウスカンパニー",
    "home.hero.title_line1": "日本在地的",
    "home.hero.title_line2": "不動產實務夥伴",
    "home.hero.desc": "我們不只介紹物件，更理解持有與經營。從取得、持有、管理、開發、營運到出售，以15年實務經驗協助客戶做出更完整的判斷。",
    "home.hero.consult": "預約諮詢",
    "home.hero.view_properties": "探索主要業務",
    "home.stat.experience_label": "EXPERIENCE",
    "home.stat.experience_val": "15年實務經驗",
    "home.stat.certified_label": "CERTIFIED",
    "home.stat.certified_val": "正式宅建業執照",
    "home.stat.global_label": "GLOBAL",
    "home.stat.global_val": "國際雙語服務",
    "home.stat.license_label": "LICENSE",
    "home.stat.license_val": "神奈川縣知事 (1) 第32070號",



    // Home - Major Businesses (04 主要業務 I & 05 主要業務 II)
    "home.services.tag": "CORE BUSINESSES",
    "home.services.title": "主要業務範疇",
    "home.services.desc": "主要業務涵蓋交易、管理與價值提升。從土地到營運，具備完整實務經驗。",
    
    // Business 1
    "home.biz1.num": "01",
    "home.biz1.title": "不動產買賣仲介",
    "home.biz1.desc": "住宅、收益型不動產、商業用不動產及土地的購買與出售。",
    "home.biz1.item1": "物件搜尋與現場確認",
    "home.biz1.item2": "價格及交易條件交涉",
    "home.biz1.item3": "契約、交屋與登記協調",

    // Business 2
    "home.biz2.num": "02",
    "home.biz2.title": "不動產租賃及管理",
    "home.biz2.desc": "協助房東處理日常管理、租賃及修繕事務，確保收益穩定。",
    "home.biz2.item1": "招租與租約管理",
    "home.biz2.item2": "租金、退租與修繕",
    "home.biz2.item3": "租賃糾紛相關應對",

    // Business 3
    "home.biz3.num": "03",
    "home.biz3.title": "不動產收購再販",
    "home.biz3.desc": "依據市場與利用方式，提升物件價值後重新出售。",
    "home.biz3.item1": "物件收購與市場判斷",
    "home.biz3.item2": "整修及價值提升",
    "home.biz3.item3": "重新定位與出售",

    // Business 4
    "home.biz4.num": "04",
    "home.biz4.title": "土地開發及自地自建",
    "home.biz4.desc": "具備土地評估、土地利用規劃、自地自建及土地開發相關經驗。",
    "home.biz4.item1": "從建築、用途及未來收益角度判斷土地價值",
    "home.biz4.item2": "土地利用規劃與建築法規評估",
    "home.biz4.item3": "自地自建專案全流程規劃與落實",

    // Business 5
    "home.biz5.num": "05",
    "home.biz5.title": "住宿設施營運",
    "home.biz5.desc": "實際從事民宿及住宿設施營運，具備從物件取得到營運管理的實務經驗。",
    "home.biz5.item1": "物件取得與合法執照取得",
    "home.biz5.item2": "設施設置與空間規格規劃",
    "home.biz5.item3": "營運管理與多語系旅客應對",

    // Home - Perspective / 特色 (03 判斷視角 & 07 我們的特點)
    "home.perspective.tag": "OUR PERSPECTIVE",
    "home.perspective.title": "站在實際持有者的立場",
    "home.perspective.desc": "我們的差異，在於不只具備仲介經驗，也擁有房東、投資、管理、開發及實際營運經驗。我們重視的不是單純完成交易，而是確認客戶購買的不動產是否符合實際目的。",
    "home.perspective.item1_title": "物件本身的價值",
    "home.perspective.item1_desc": "確認地段、建物、權利與市場條件。",
    "home.perspective.item2_title": "實際持有成本",
    "home.perspective.item2_desc": "將稅費、管理、修繕與資金成本納入。",
    "home.perspective.item3_title": "租賃及營運風險",
    "home.perspective.item3_desc": "評估租戶、空置、收入與營運穩定性。",
    "home.perspective.item4_title": "修繕及管理問題",
    "home.perspective.item4_desc": "理解建物老化、設備與日常管理負擔。",
    "home.perspective.item5_title": "土地利用與開發",
    "home.perspective.item5_desc": "判斷用途、建築及未來利用可能性。",
    "home.perspective.item6_title": "出售及退場方式",
    "home.perspective.item6_desc": "購買前即考慮流動性、稅務與未來買家。",

    // Home - Advisor Profile (02 代表人背景)
    "home.advisor.tag": "REPRESENTATIVE",
    "home.advisor.title": "15年不動產實務\n來自親自參與每一個環節",
    "home.advisor.name": "黃經祐",
    "home.advisor.role": "代表人 ｜ 房東 ｜ 不動產投資人",
    "home.advisor.desc": "在日本累積約15年的不動產實務經驗。實際參與經驗涵蓋物件購買、出租管理與修繕、不動產仲介、自地自建專案、土地評估、利用規劃與開發，以及住宿設施取得與營運。不是只從仲介成交看物件，而是從實際持有與經營結果判斷。",
    "home.advisor.cta": "查看完整簡介",

    // Home - Process (06 服務流程)
    "home.process.tag": "PROCESS",
    "home.process.title": "完整實務服務流程",
    "home.process.desc": "利用日本當地的實務經驗，協助海外客戶完成從選擇到出售的完整流程。",
    "home.process.step1.title": "物件選擇",
    "home.process.step1.desc": "依據自住或投資目標，精選符合條件與實際持有價值的優質標的。",
    "home.process.step2.title": "調查",
    "home.process.step2.desc": "深入調查地段、建物狀況、法規權利、持有成本與修繕歷史。",
    "home.process.step3.title": "契約",
    "home.process.step3.desc": "專業交涉價格與交易條件，提供清晰合規的契約審閱與法定說明。",
    "home.process.step4.title": "交屋",
    "home.process.step4.desc": "協調款項交付、所有權移轉登記及現場點交等所有法定手續。",
    "home.process.step5.title": "購買後管理",
    "home.process.step5.desc": "涵蓋租賃招租、日常修繕、營運維護與收支管理，讓海外持有無後顧之憂。",
    "home.process.step6.title": "未來出售",
    "home.process.step6.desc": "預先評估市場流動性與稅務規劃，在最佳時機協助退場獲利。",
    "home.process.cta": "探索完整服務項目",

    // Services Page
    "services.title": "Yellow House - 服務項目 | 株式会社イエローハウスカンパニー",
    "services.banner.tag": "SERVICES",
    "services.banner.h1": "主要業務與服務項目",
    "services.banner.desc": "主要業務涵蓋交易、管理與價值提升。從取得、持有、管理、開發、營運到出售，以實際經驗協助客戶做出更完整的判斷。",
    "services.tag1": "不動產買賣仲介",
    "services.tag2": "不動產租賃及管理",
    "services.tag3": "不動產收購再販",
    "services.tag4": "土地開發及自地自建",
    "services.tag5": "住宿設施營運",
    "services.tag6": "海外置產顧問",
    "services.steps.title": "完整購置與持有流程",
    "services.flow.title": "服務流程 / SERVICE FLOW",
    "services.taxes.title": "相關費用及稅金概要",
    "services.taxes.buy_label": "購入時",
    "services.taxes.buy_val": "仲介手續費 / 不動產取得稅 / 印花稅 / 登記免許稅 / 固都稅精算",
    "services.taxes.hold_label": "持有期間",
    "services.taxes.hold_val": "固定資產稅 / 都市計畫稅 / 管理費 / 修繕積立金 / 所得稅申報",
    "services.taxes.sell_label": "出售時",
    "services.taxes.sell_val": "讓渡所得稅 / 仲介手續費 / 登記手續費",
    "services.mgmt.title": "租賃及日常管理業務",
    "services.mgmt.desc": "協助房東處理日常管理、租賃及修繕事務，以實際房東與經營者的經驗，讓身在海外的您安心持有日本資產。",
    "services.mgmt.item1": "招租與租約管理（嚴格審查承租人資格）",
    "services.mgmt.item2": "租金收取、匯款與日常收支明細管理",
    "services.mgmt.item3": "建物老化維護、設備修繕與日常管理負擔減輕",
    "services.mgmt.item4": "租賃糾紛應對、退租點交與原狀恢復落實",
    "services.cta.title": "討論您的日本不動產需求",
    "services.cta.btn": "預約專業諮詢",

    // Company Page (COMPANY INFORMATION 唯一依據)
    "company.title": "Yellow House - 公司簡介 | 株式会社イエローハウスカンパニー",
    "company.banner.tag": "COMPANY PROFILE",
    "company.banner.h1": "日本在地的不動產實務夥伴",
    "company.banner.desc": "從取得、持有、管理、開發、營運到出售，以實際經驗協助客戶做出更完整的判斷。",
    "company.rep.tag": "代表人背景",
    "company.rep.headline": "15年不動產實務，\n來自親自參與每一個環節。",
    "company.rep.p1": "株式会社イエローハウスカンパニー是一家立足日本，並持有正式宅地建物取引業執照的不動產公司。我們不只介紹物件，更理解持有與經營。",
    "company.rep.p2": "我們從買方、房東、投資人及經營者的角度，協助客戶判斷物件的價值、成本與風險。不以成交為唯一目的，而是確認物件是否適合實際持有與經營。",
    "company.overview.tag": "COMPANY INFORMATION",
    "company.overview.title": "公司基本資料",
    "company.overview.name_label": "公司名稱",
    "company.overview.name_val": "株式会社イエローハウスカンパニー (YELLOW HOUSE COMPANY)",
    "company.overview.loc_label": "公司地址",
    "company.overview.loc_val": "神奈川縣伊勢原市櫻台1-22-15\nネオハイツ伊勢原112 (〒259-1132)",
    "company.overview.lic_label": "執照",
    "company.overview.lic_val": "神奈川縣知事（1）第32070號",
    "company.overview.email_label": "Email",
    "company.overview.email_val": "contact@yellowhouse.jp",
    "company.overview.phone_label": "電話",
    "company.overview.phone_val": "-",
    "company.overview.hours_label": "營業時間",
    "company.overview.hours_val": "週一至週五 09:00 - 18:00 (JST)\n週末與日本國定假日可預約線上諮詢",
    "company.quote": "「不以成交為唯一目的，\n而是確認物件是否適合實際持有與經營。」",
    "company.quote_desc": "我們的差異，在於站在實際持有者的立場。不只具備仲介經驗，也擁有房東、投資、管理、開發及實際營運經驗，為您提供最務實的判斷。",
    "company.visit.tag": "OUR OFFICE",
    "company.visit.title": "神奈川 本社",
    "company.visit.btn": "前往 Google 地圖導航",

    // Cases Page
    "cases.title": "Yellow House - 實績案例",
    "cases.banner.tag": "PORTFOLIO",
    "cases.banner.h1": "實績案例與精選項目",
    "cases.banner.desc": "涵蓋高級自住住宅、收益型商辦、土地開發與住宿設施，展現我們在買賣、管理、整修與營運上的深厚實務經驗。",
    "cases.filter.all": "全部實績",
    "cases.filter.res": "住宅・自住",
    "cases.filter.com": "商用・收益型",
    "cases.card.view_detail": "查看詳情",
    "cases.card.inquire": "諮詢此標的",
    "cases.c1.tag": "高級住宅・東京港區",
    "cases.c1.title": "港區頂級高空景觀名邸",
    "cases.c1.desc": "位於東京核心地段的高級自住不動產，具備優異的建物品質、稀缺地段與完善物業管理，提供海外買家極致的自住生活體驗。",
    "cases.c1.specs": "專有面積 182㎡ ｜ 3LDK ｜ 永久產權",
    "cases.c2.tag": "收益商辦・東京涉谷",
    "cases.c2.title": "涉谷核心收益型商用大樓",
    "cases.c2.desc": "全棟滿租之核心商辦資產，具備穩定長期租金現金流，經過收益架構重整與修繕管理優化，實現穩健年化回報。",
    "cases.c2.specs": "整棟 RC 6階建 ｜ 滿租營運中 ｜ 永久產權",
    "cases.c3.tag": "自住名邸・東京涉谷",
    "cases.c3.title": "涉谷區靜謐住宅區獨棟別墅",
    "cases.c3.desc": "結合現代日式建築美學與綠意庭園的頂級自住住宅，兼具都心生活便利性與高度私密性。",
    "cases.c3.specs": "土地面積 210㎡ ｜ 建物面積 260㎡ ｜ 4LDK",
    "cases.c4.tag": "商業旗艦・東京中央區",
    "cases.c4.title": "中央區精品商業街角旗艦店",
    "cases.c4.desc": "位處高人流商業精華地段，具備極佳品牌展示效應與抗跌性，提供長期穩定租約與收益保障。",
    "cases.c4.specs": "整棟 4階建 ｜ 商業核心區 ｜ 永久產權",
    "cases.c5.tag": "頂級住宅・東京港區",
    "cases.c5.title": "六本木高空全景天際豪邸",
    "cases.c5.desc": "俯瞰東京鐵塔與都會天際線的代表性豪宅，配備24小時飯店式禮賓服務與專屬停車位。",
    "cases.c5.specs": "專有面積 245㎡ ｜ 3LDK 頂層",
    "cases.c6.tag": "住宿設施・京都東山",
    "cases.c6.title": "京都傳統町家活化住宿設施",
    "cases.c6.desc": "實際取得並進行合法住宿設施營運規劃，保留百年木構文化精髓並導入現代舒適設施與專業旅客接待系統。",
    "cases.c6.specs": "土地利用規劃 ｜ 民宿合法執照 ｜ 營運管理",
    "cases.c7.tag": "別墅自建・神奈川橫濱",
    "cases.c7.title": "橫濱港景自地自建海景住宅",
    "cases.c7.desc": "從土地取得評估、建築規劃設計到全流程營造自建，打造無可取代的海景自住居所。",
    "cases.c7.specs": "自地自建專案 ｜ 土地面積 350㎡ ｜ 永久產權",
    "cases.c8.tag": "收益公寓・東京新宿",
    "cases.c8.title": "新宿御苑收益型集合住宅",
    "cases.c8.desc": "緊鄰御苑綠地的優質收益型公寓，透過專業租賃管理與定期維護修繕，常年維持高稼動率。",
    "cases.c8.specs": "整棟 RC 5階建 ｜ 16戶 ｜ 租賃管理中",
    "cases.c9.tag": "莊園別墅・長野輕井澤",
    "cases.c9.title": "輕井澤森林度假別墅",
    "cases.c9.desc": "坐落於百年落葉松林間的四季度假宅邸，兼具自用休閒與非自住期間之託管收益潛力。",
    "cases.c9.specs": "敷地面積 850㎡ ｜ 溫泉引進 ｜ 4LDK",

    // News Page
    "news.title": "Yellow House - 最新消息 | 株式会社イエローハウスカンパニー",
    "news.banner.tag": "NEWS & UPDATES",
    "news.banner.h1": "最新消息與市場動態",
    "news.banner.desc": "株式会社イエローハウスカンパニー的最新業務進展、日本不動產市場洞察與實務專題分享。",
    "news.featured_label": "精選動態",
    "news.featured.date": "2026年3月",
    "news.featured.tag": "實務專題",
    "news.featured.title": "立足日本的在地實務夥伴：從取得、持有到營運的完整視角",
    "news.featured.desc": "我們不只介紹物件，更從買方、房東、投資人與經營者的多重視角，協助海外客戶全面評估日本不動產的實際價值、持有成本與營運風險。",
    "news.category.title": "分類",
    "news.category.all": "全部動態",
    "news.category.insights": "市場洞察",
    "news.category.market": "實務觀點",
    "news.category.corp": "公司公告",
    "news.category.media": "媒體報導",
    "news.read_more": "閱讀專題",

    // Careers Page
    "careers.title": "Yellow House - 招募公告 | 株式会社イエローハウスカンパニー",
    "careers.banner.tag": "CAREERS",
    "careers.banner.h1": "加入我們的實務專業團隊",
    "careers.banner.desc": "我們尋找熱愛日本不動產、具備誠信與實務精神的夥伴，共同為國際客戶提供最可信賴的顧問服務。",
    "careers.open_positions": "OPEN POSITIONS",
    "careers.job1.type": "全職",
    "careers.job1.location": "日本 神奈川 / 東京",
    "careers.job1.title": "不動產顧問與仲介專員（歡迎雙語人才）",
    "careers.job1.desc": "負責海外客戶之不動產諮詢、物件現地調查、買賣及租賃仲介協調。我們重視實務能力的培養，提供完整的日本宅建業務支持。",
    "careers.quote": "「我們重視的是站在客戶立場的真誠與專業。每一位同仁都是為客戶把關資產實質價值的關鍵角色。」",
    "careers.quote_author": "黃經祐",
    "careers.quote_dept": "代表人",
    "careers.join.title": "有興趣加入我們嗎？",
    "careers.join.desc": "歡迎將您的履歷與自我介紹發送給我們，開啟您在日本不動產領域的專業職涯。",
    "careers.join.btn": "發送應徵信件",

    // Contact Page (COMPANY INFORMATION 唯一依據)
    "contact.title": "Yellow House - 聯絡我們 | 株式会社イエローハウスカンパニー",
    "contact.banner.tag": "CONTACT US",
    "contact.banner.h1": "聯絡我們",
    "contact.banner.desc": "日本在地的實務不動產夥伴。無論您需要購置自住豪宅、投資收益型資產、租賃管理、自地自建或民宿營運諮詢，歡迎隨時與我們聯繫。",
    "contact.form.company": "公司／組織名稱 (選填)",
    "contact.form.name": "姓名",
    "contact.form.email": "電子郵件",
    "contact.form.phone": "聯絡電話 (選填)",
    "contact.form.type": "諮詢主要業務",
    "contact.form.type_placeholder": "請選擇業務項目",
    "contact.form.type_res": "01 不動產買賣仲介（住宅 / 自住）",
    "contact.form.type_com": "01 不動產買賣仲介（商業用 / 收益型）",
    "contact.form.type_mgmt": "02 不動產租賃及管理",
    "contact.form.type_resale": "03 不動產收購再販",
    "contact.form.type_dev": "04 土地開發及自地自建",
    "contact.form.type_hospitality": "05 住宿設施營運",
    "contact.form.type_other": "其他諮詢事項",
    "contact.form.message": "諮詢內容與需求",
    "contact.form.submit": "送出諮詢表單",
    "contact.form.submitting": "傳送中...",
    "contact.form.success": "諮詢已成功送出！我們將儘速與您聯繫",
    
    "contact.info.company_name_label": "公司名稱",
    "contact.info.company_name_val": "株式会社イエローハウスカンパニー\n(YELLOW HOUSE COMPANY)",
    "contact.info.hq_label": "公司地址",
    "contact.info.hq_val": "神奈川縣伊勢原市櫻台1-22-15\nネオハイツ伊勢原112 (〒259-1132)",
    "contact.info.license_label": "執照",
    "contact.info.license_val": "神奈川縣知事（1）第32070號",
    "contact.info.contact_label": "Email",
    "contact.info.contact_val": "contact@yellowhouse.jp",
    "contact.info.phone_label": "電話",
    "contact.info.phone_val": "-",
    "contact.info.hours_label": "營業時間",
    "contact.info.hours_val": "週一至週五 09:00 - 18:00 (JST)\n週末與日本國定假日可預約線上諮詢",
    "contact.quote": "「從取得、持有、管理、開發、營運到出售，以實際經驗協助客戶做出更完整的判斷。」",

    // Currency
    "currency.label": "貨幣",
    "currency.updated": "匯率更新時間",
    "currency.updated_cached": "匯率更新時間（離線快取）",
    "currency.unavailable": "匯率暫時無法取得，僅顯示日圓價格",
    "currency.approx": "約",
    "currency.disclaimer": "美元金額為依最新可取得匯率換算之參考值，實際金額可能因匯率變動而異。",
    "price.label": "物件價格"
  },
  en: {
    // Nav
    "nav.home": "HOME",
    "nav.services": "SERVICES",
    "nav.company": "COMPANY",
    "nav.cases": "PORTFOLIO",
    "nav.news": "NEWS",
    "nav.careers": "CAREERS",
    "nav.contact": "CONTACT",

    // Common CTA Banner
    "cta.title": "Begin Your Real Estate Journey in Japan",
    "cta.button": "SCHEDULE CONSULTATION",

    // Footer
    "footer.desc": "Based in Japan with an official Real Estate Brokerage License. Providing end-to-end practical advisory from brokerage, property management, and value-add resale to land development, bespoke builds, and hospitality operations.",
    "footer.nav": "NAVIGATION",
    "footer.careers": "CAREERS",
    "footer.location": "LOCATION",
    "footer.opps": "Opportunities",
    "footer.culture": "Culture",
    "footer.contact_hr": "Contact Us",
    "footer.copyright": "© 2026 YELLOW HOUSE COMPANY Inc. (株式会社イエローハウスカンパニー). ALL RIGHTS RESERVED.",
    "footer.privacy": "PRIVACY POLICY",
    "footer.terms": "TERMS OF SERVICE",
    "footer.map_label": "Kanagawa HQ",

    // Home
    "home.title": "Yellow House - Your Practical Real Estate Partner in Japan | Yellow House Company Inc.",
    "home.hero.title_line1": "Your Practical Partner in",
    "home.hero.title_line2": "Japan Real Estate",
    "home.hero.desc": "We don't just introduce properties; we understand what it takes to own and operate them. From acquisition, holding, management, development, and operations to resale, our 15 years of hands-on experience empower you to make informed decisions.",
    "home.hero.consult": "BOOK CONSULTATION",
    "home.hero.view_properties": "EXPLORE BUSINESSES",
    "home.stat.experience_label": "EXPERIENCE",
    "home.stat.experience_val": "15 Years Track Record",
    "home.stat.certified_label": "CERTIFIED",
    "home.stat.certified_val": "Licensed Real Estate Broker",
    "home.stat.global_label": "GLOBAL",
    "home.stat.global_val": "Bilingual Advisory",
    "home.stat.license_label": "LICENSE",
    "home.stat.license_val": "Governor of Kanagawa (1) No. 32070",

    // Home - Focus Areas (06 Overseas Client Focus)
    "home.focus.tag": "OVERSEAS CLIENT FOCUS",
    "home.focus.title": "Two Core Directions for International Clients",
    "home.focus.desc": "Prioritizing European and North American clients, alongside investors from Taiwan and the greater Chinese-speaking world. We guide overseas buyers through the complete lifecycle from selection to eventual resale.",
    "home.focus1.num": "01",
    "home.focus1.tag": "PRIME RESIDENTIAL",
    "home.focus1.title": "Tokyo Prime Residential\n(JPY 100M+)",
    "home.focus1.desc": "Curating prime Tokyo residential estates that harmonize architectural quality, lifestyle comfort, and enduring capital preservation.",
    "home.focus1.cta": "EXPLORE RESIDENTIAL",
    "home.focus2.num": "02",
    "home.focus2.tag": "COMMERCIAL & INCOME",
    "home.focus2.title": "Commercial & Income-Generating\nProperty Investment",
    "home.focus2.desc": "Delivering rigorous yield calculations and asset structuring for investors seeking reliable cash flows and capital growth.",
    "home.focus2.cta": "EXPLORE INVESTMENT",

    // Home - Major Businesses (04 & 05)
    "home.services.tag": "CORE BUSINESSES",
    "home.services.title": "Our Core Business Scope",
    "home.services.desc": "Covering transactions, management, and value enhancement from land to full operations with comprehensive practical expertise.",
    
    // Business 1
    "home.biz1.num": "01",
    "home.biz1.title": "Real Estate Brokerage",
    "home.biz1.desc": "Acquisition and sale of residential estates, income-generating assets, commercial properties, and land.",
    "home.biz1.item1": "Property search & on-site due diligence",
    "home.biz1.item2": "Price & transaction terms negotiation",
    "home.biz1.item3": "Contract, closing & title registration coordination",

    // Business 2
    "home.biz2.num": "02",
    "home.biz2.title": "Leasing & Property Management",
    "home.biz2.desc": "Assisting landlords with day-to-day operations, tenant placement, and maintenance to safeguard steady returns.",
    "home.biz2.item1": "Tenant recruitment & lease administration",
    "home.biz2.item2": "Rent collection, move-outs & repair management",
    "home.biz2.item3": "Tenancy dispute resolution & legal compliance",

    // Business 3
    "home.biz3.num": "03",
    "home.biz3.title": "Property Acquisition & Value-Add Resale",
    "home.biz3.desc": "Enhancing asset value through strategic renovation and repurposing before repositioning in the market.",
    "home.biz3.item1": "Property acquisition & market valuation",
    "home.biz3.item2": "Architectural refurbishment & value enhancement",
    "home.biz3.item3": "Strategic repositioning & resale execution",

    // Business 4
    "home.biz4.num": "04",
    "home.biz4.title": "Land Development & Bespoke Construction",
    "home.biz4.desc": "Proven track record in site evaluation, land utilization planning, bespoke construction, and property development.",
    "home.biz4.item1": "Evaluating land value from zoning, design & yield angles",
    "home.biz4.item2": "Architectural planning tailored to market demands",
    "home.biz4.item3": "End-to-end custom build project management",

    // Business 5
    "home.biz5.num": "05",
    "home.biz5.title": "Hospitality & Accommodation Operations",
    "home.biz5.desc": "Hands-on experience in operating licensed vacation rentals and accommodation facilities from acquisition to daily guest hosting.",
    "home.biz5.item1": "Property acquisition & licensing compliance",
    "home.biz5.item2": "Facility setup & interior spatial planning",
    "home.biz5.item3": "Daily operational management & guest communications",

    // Home - Perspective (03 & 07)
    "home.perspective.tag": "OUR PERSPECTIVE",
    "home.perspective.title": "Standing from the Owner & Operator's Perspective",
    "home.perspective.desc": "Our distinction lies in combining brokerage expertise with real-world experience as landlords, investors, property managers, developers, and hospitality operators. We prioritize whether an asset truly serves your ownership goals over merely closing a deal.",
    "home.perspective.item1_title": "Intrinsic Asset Value",
    "home.perspective.item1_desc": "Evaluating location, structural integrity, legal rights, and market conditions.",
    "home.perspective.item2_title": "Real Holding Costs",
    "home.perspective.item2_desc": "Factoring in taxes, management fees, repair reserves, and financing costs.",
    "home.perspective.item3_title": "Leasing & Operating Risks",
    "home.perspective.item3_desc": "Assessing tenant quality, vacancy risk, cash flow stability, and operational friction.",
    "home.perspective.item4_title": "Maintenance & Aging Dynamics",
    "home.perspective.item4_desc": "Understanding building depreciation, equipment upkeep, and daily management burdens.",
    "home.perspective.item5_title": "Land Utilization & Development",
    "home.perspective.item5_desc": "Analyzing zoning allowances, architectural potential, and future upside.",
    "home.perspective.item6_title": "Exit Strategy & Resale Liquidity",
    "home.perspective.item6_desc": "Evaluating secondary market liquidity, future buyer profiles, and tax implications before acquisition.",

    // Home - Advisor Profile (02)
    "home.advisor.tag": "REPRESENTATIVE",
    "home.advisor.title": "15 Years of Practical Experience\nRooted in Every Stage of Real Estate",
    "home.advisor.name": "Kei-Yu Huang",
    "home.advisor.role": "Representative ｜ Landlord ｜ Real Estate Investor",
    "home.advisor.desc": "Accumulating approximately 15 years of hands-on real estate practice in Japan. Directly engaged in acquisitions, leasing management, renovations, brokerage, bespoke developments, land planning, and hospitality facility operations. We evaluate properties through the lens of actual ownership and operational success, never just transactional closing.",
    "home.advisor.cta": "VIEW COMPANY PROFILE",

    // Home - Process (06)
    "home.process.tag": "WORKFLOW",
    "home.process.title": "Complete 6-Step Service Workflow",
    "home.process.desc": "Leveraging deep local Japan experience to support overseas clients through every phase from selection to profitable exit.",
    "home.process.step1.title": "Property Selection",
    "home.process.step1.desc": "Carefully curating assets aligned with your residential standards or investment targets.",
    "home.process.step2.title": "Investigation & Due Diligence",
    "home.process.step2.desc": "Conducting on-site surveys, structural audits, legal checks, and full cost assessments.",
    "home.process.step3.title": "Contract & Negotiation",
    "home.process.step3.desc": "Negotiating optimal terms and providing clear, legally compliant bilingual contract reviews.",
    "home.process.step4.title": "Settlement & Closing",
    "home.process.step4.desc": "Coordinating fund transfers, official title registration, and formal key handover.",
    "home.process.step5.title": "Post-Purchase Management",
    "home.process.step5.desc": "Handling tenant leasing, regular maintenance, repair management, and financial accounting.",
    "home.process.step6.title": "Future Exit & Resale",
    "home.process.step6.desc": "Assessing market liquidity and tax implications to facilitate timely, profitable divestment.",
    "home.process.cta": "EXPLORE ALL SERVICES",

    // Services Page
    "services.title": "Yellow House - Services | Yellow House Company Inc.",
    "services.banner.tag": "SERVICES",
    "services.banner.h1": "Core Businesses & Services",
    "services.banner.desc": "Encompassing transactions, management, and value creation. From acquisition, holding, management, development, and operations to resale, our hands-on experience empowers you to make informed decisions.",
    "services.tag1": "Real Estate Brokerage",
    "services.tag2": "Leasing & Property Management",
    "services.tag3": "Property Acquisition & Resale",
    "services.tag4": "Land Development & Builds",
    "services.tag5": "Hospitality Operations",
    "services.tag6": "Cross-Border Advisory",
    "services.flagA.tag": "Overseas Client Direction I",
    "services.flagA.box_title": "Tokyo Prime Residential (JPY 100M+)",
    "services.flagA.box_desc": "Prioritizing international and cross-border buyers seeking trophy residences with enduring value and premier living environments.",
    "services.flagA.desc": "Viewing every property from the owner-occupier standpoint, we analyze neighborhood amenities, school districts, craftsmanship, and long-term liquidity. We provide end-to-end guidance from search and diligence to post-handover support.",
    "services.flagB.tag": "Overseas Client Direction II",
    "services.flagB.box_title": "Commercial & Income-Generating Investment",
    "services.flagB.box_desc": "Encompassing office buildings, retail assets, and multi-family residential complexes evaluated with realistic holding yields.",
    "services.flagB.desc": "Looking beyond superficial headline yields, we incorporate taxes, management fees, repair reserves, vacancy buffers, and future exit liquidity into comprehensive financial models.",
    "services.steps.title": "Comprehensive Workflow",
    "services.flow.title": "SERVICE FLOW",
    "services.taxes.title": "Associated Costs & Taxes Summary",
    "services.taxes.buy_label": "Upon Purchase",
    "services.taxes.buy_val": "Brokerage Fee / Property Acquisition Tax / Stamp Duty / Registration Tax / Prorated Fixed Asset Tax",
    "services.taxes.hold_label": "Holding Period",
    "services.taxes.hold_val": "Fixed Asset Tax / City Planning Tax / Building Management Fee / Repair Reserve / Income Tax Filing",
    "services.taxes.sell_label": "Upon Sale",
    "services.taxes.sell_val": "Capital Gains Tax / Brokerage Commission / Registration Fees",
    "services.mgmt.title": "Leasing & Property Management Operations",
    "services.mgmt.desc": "Assisting owners with tenant placement, rent collection, and repairs. Our hands-on landlord experience ensures your Japanese property is managed with complete peace of mind.",
    "services.mgmt.item1": "Tenant recruitment & strict background verification",
    "services.mgmt.item2": "Rent collection, overseas remittance & financial reporting",
    "services.mgmt.item3": "Preventative building upkeep, equipment repairs & burden mitigation",
    "services.mgmt.item4": "Dispute mediation, move-out inspections & restoration oversight",
    "services.cta.title": "Discuss Your Japanese Real Estate Strategy",
    "services.cta.btn": "SCHEDULE CONSULTATION",

    // Company Page (COMPANY INFORMATION 唯一依據)
    "company.title": "Yellow House - Company Profile | Yellow House Company Inc.",
    "company.banner.tag": "COMPANY PROFILE",
    "company.banner.h1": "Your Practical Real Estate Partner in Japan",
    "company.banner.desc": "From acquisition, holding, management, development, and operations to resale, our hands-on experience empowers you to make informed decisions.",
    "company.rep.tag": "REPRESENTATIVE PROFILE",
    "company.rep.headline": "15 Years of Practical Experience,\nRooted in Every Single Stage.",
    "company.rep.p1": "Yellow House Company Inc. (株式会社イエローハウスカンパニー) is a licensed Japanese real estate corporation holding an official Real Estate Brokerage License. We don't just introduce properties; we deeply understand what it takes to own and operate them.",
    "company.rep.p2": "From the multi-faceted perspectives of buyers, landlords, investors, and operators, we assist clients in evaluating true asset value, total cost of ownership, and operational risks. Our goal is never just closing a transaction, but confirming whether an asset is genuinely suited for long-term ownership and operation.",
    "company.overview.tag": "COMPANY INFORMATION",
    "company.overview.title": "Corporate Overview",
    "company.overview.name_label": "Company Name",
    "company.overview.name_val": "Yellow House Company Inc. (株式会社イエローハウスカンパニー)",
    "company.overview.rep_label": "Representative",
    "company.overview.rep_val": "Kei-Yu Huang (Representative Director ｜ Landlord ｜ Investor)",
    "company.overview.lic_label": "License Number",
    "company.overview.lic_val": "Governor of Kanagawa (1) No. 32070",
    "company.overview.biz_label": "Core Businesses",
    "company.overview.biz_val1": "Real Estate Brokerage, Leasing Management, Value-Add Resale",
    "company.overview.biz_val2": "Land Development, Bespoke Construction, Hospitality Operations",
    "company.overview.biz_val3": "Cross-Border Real Estate Advisory & Comprehensive Support",
    "company.overview.loc_label": "Address",
    "company.overview.loc_val": "#112 Neo Heights Isehara, 1-22-15 Sakuradai,\nIsehara-shi, Kanagawa 259-1132, Japan",
    "company.quote": "“Not merely closing transactions, but confirming whether an asset is truly suited for actual ownership and operations.”",
    "company.quote_desc": "Our distinction lies in standing firmly in the shoes of actual property owners. Beyond agency brokerage, our direct experience in holding, managing, developing, and operating real estate ensures you receive the most practical, objective guidance.",
    "company.visit.tag": "OUR OFFICE",
    "company.visit.title": "Kanagawa Headquarters",
    "company.visit.btn": "OPEN GOOGLE MAPS",

    // Cases Page
    "cases.title": "Yellow House - Case Studies",
    "cases.banner.tag": "PORTFOLIO",
    "cases.banner.h1": "Selected Portfolio & Case Studies",
    "cases.banner.desc": "Spanning prime residential homes, commercial office buildings, land developments, and hospitality assets—demonstrating our deep practical track record across acquisitions, management, and operations.",
    "cases.filter.all": "ALL PROJECTS",
    "cases.filter.res": "RESIDENTIAL",
    "cases.filter.com": "COMMERCIAL & INCOME",
    "cases.card.view_detail": "VIEW DETAILS",
    "cases.card.inquire": "INQUIRE PROPERTY",
    "cases.c1.tag": "PRIME RESIDENTIAL・TOKYO MINATO",
    "cases.c1.title": "Minato Sky View Penthouse Sanctuary",
    "cases.c1.desc": "Prime residential estate in central Tokyo featuring panoramic skyline views, exceptional building specs, and full concierge management.",
    "cases.c1.specs": "Floor Area 182㎡ ｜ 3LDK ｜ Freehold",
    "cases.c2.tag": "INCOME COMMERCIAL・TOKYO SHIBUYA",
    "cases.c2.title": "Shibuya Core Commercial Office Building",
    "cases.c2.desc": "Fully-leased commercial office asset in central Shibuya generating strong cash flows, with optimized leasing structures and building management.",
    "cases.c2.specs": "Whole Building RC 6-Story ｜ 100% Leased ｜ Freehold",
    "cases.c3.tag": "BOUTIQUE RESIDENCE・TOKYO SHIBUYA",
    "cases.c3.title": "Shibuya Quiet Enclave Detached Residence",
    "cases.c3.desc": "Bespoke detached residence harmonizing modernist Japanese aesthetics and private landscaped gardens in an exclusive residential enclave.",
    "cases.c3.specs": "Site 210㎡ ｜ Floor 260㎡ ｜ 4LDK",
    "cases.c4.tag": "RETAIL COMMERCIAL・TOKYO CHUO",
    "cases.c4.title": "Chuo District Prime Corner Commercial Asset",
    "cases.c4.desc": "High-footfall corner retail property offering supreme brand visibility, defensive valuation, and long-term secure corporate leases.",
    "cases.c4.specs": "Whole Building 4-Story ｜ Commercial Core ｜ Freehold",
    "cases.c5.tag": "PRIME RESIDENTIAL・TOKYO MINATO",
    "cases.c5.title": "Roppongi Skyline Panoramic Penthouse",
    "cases.c5.desc": "Trophy residential penthouse overlooking Tokyo Tower with 24-hour hotel-grade concierge services and private parking.",
    "cases.c5.specs": "Floor Area 245㎡ ｜ 3LDK Duplex",
    "cases.c6.tag": "HOSPITALITY・KYOTO HIGASHIYAMA",
    "cases.c6.title": "Kyoto Century Machiya Heritage Hospitality Facility",
    "cases.c6.desc": "Acquisition and full licensing for traditional Kyoto machiya hospitality operations, blending heritage carpentry with modern amenities.",
    "cases.c6.specs": "Land Planning ｜ Licensed Minpaku ｜ Operations",
    "cases.c7.tag": "BESPOKE BUILD・KANAGAWA YOKOHAMA",
    "cases.c7.title": "Yokohama Bay View Bespoke Residence",
    "cases.c7.desc": "Comprehensive project management from site acquisition and architectural design to full custom construction overlooking Yokohama port.",
    "cases.c7.specs": "Bespoke Build ｜ Site 350㎡ ｜ Freehold",
    "cases.c8.tag": "INCOME MULTI-FAMILY・TOKYO SHINJUKU",
    "cases.c8.title": "Shinjuku Gyoen Income-Generating Multi-Family Tower",
    "cases.c8.desc": "Boutique residential apartment building adjacent to Gyoen parklands, maintaining high occupancy through proactive asset management.",
    "cases.c8.specs": "Whole Building RC 5-Story ｜ 16 Units ｜ Managed",
    "cases.c9.tag": "FOREST RETREAT・NAGANO KARUIZAWA",
    "cases.c9.title": "Old Karuizawa Four-Season Forest Villa",
    "cases.c9.desc": "Secluded four-season villa nestled among centenary larches, offering year-round personal retreat alongside flexible hospitality hosting.",
    "cases.c9.specs": "Site 850㎡ ｜ Natural Onsen ｜ 4LDK",

    // News Page
    "news.title": "Yellow House - Press & News | Yellow House Company Inc.",
    "news.banner.tag": "NEWS & UPDATES",
    "news.banner.h1": "News & Market Updates",
    "news.banner.desc": "Latest corporate announcements, Japan real estate market insights, and practical advisory topics from Yellow House Company.",
    "news.featured_label": "FEATURED TOPIC",
    "news.featured.date": "MARCH 2026",
    "news.featured.tag": "PRACTICAL ADVISORY",
    "news.featured.title": "Your Practical Partner in Japan: A Comprehensive Perspective from Acquisition to Operations",
    "news.featured.desc": "We don't just broker transactions; we evaluate properties from the combined perspectives of buyers, landlords, investors, and operators—assessing genuine value, holding costs, and operating risks.",
    "news.category.title": "CATEGORIES",
    "news.category.all": "All Updates",
    "news.category.insights": "Market Insights",
    "news.category.market": "Practical Views",
    "news.category.corp": "Company News",
    "news.category.media": "Media Coverage",
    "news.read_more": "READ TOPIC",

    // Careers Page
    "careers.title": "Yellow House - Careers | Yellow House Company Inc.",
    "careers.banner.tag": "CAREERS",
    "careers.banner.h1": "Join Our Practical Advisory Team",
    "careers.banner.desc": "We are looking for passionate, integrity-driven talents who love Japanese real estate to deliver trustworthy advisory for international clients.",
    "careers.open_positions": "OPEN POSITIONS",
    "careers.job1.type": "FULL-TIME",
    "careers.job1.location": "KANAGAWA / TOKYO, JAPAN",
    "careers.job1.title": "Real Estate Advisor & Brokerage Specialist (Bilingual Welcomed)",
    "careers.job1.desc": "Responsible for cross-border client consultations, on-site due diligence, and transaction coordination. We provide structured training in Japan real estate practice.",
    "careers.quote": "“We value genuine professionalism rooted in the client's perspective. Every team member plays a vital role in safeguarding our clients' real asset value.”",
    "careers.quote_author": "Kei-Yu Huang",
    "careers.quote_dept": "Representative Director",
    "careers.join.title": "Interested in Joining Us?",
    "careers.join.desc": "Feel free to submit your resume and introduction to start your career in Japanese real estate.",
    "careers.join.btn": "APPLY VIA EMAIL",

    // Contact Page (COMPANY INFORMATION 唯一依據)
    "contact.title": "Yellow House - Contact | Yellow House Company Inc.",
    "contact.banner.tag": "CONTACT US",
    "contact.banner.h1": "Contact Us",
    "contact.banner.desc": "Your practical real estate partner in Japan. Whether you are seeking prime residential estates, commercial investments, leasing management, custom builds, or hospitality operations, we are here to assist.",
    "contact.form.company": "Company / Organization (Optional)",
    "contact.form.name": "Full Name",
    "contact.form.email": "Email Address",
    "contact.form.phone": "Phone Number (Optional)",
    "contact.form.type": "Inquiry Topic",
    "contact.form.type_placeholder": "Select Core Business",
    "contact.form.type_res": "01 Real Estate Brokerage (Residential / Prime)",
    "contact.form.type_com": "01 Real Estate Brokerage (Commercial / Income)",
    "contact.form.type_mgmt": "02 Leasing & Property Management",
    "contact.form.type_resale": "03 Property Acquisition & Resale",
    "contact.form.type_dev": "04 Land Development & Bespoke Construction",
    "contact.form.type_hospitality": "05 Hospitality Facility Operations",
    "contact.form.type_other": "Other Inquiries",
    "contact.form.message": "Message / Details",
    "contact.form.submit": "SUBMIT INQUIRY",
    "contact.form.submitting": "SENDING...",
    "contact.form.success": "Inquiry submitted successfully. Our team will contact you shortly.",
    
    "contact.info.company_name_label": "COMPANY NAME",
    "contact.info.company_name_val": "Yellow House Company Inc.\n(株式会社イエローハウスカンパニー)",
    "contact.info.rep_label": "REPRESENTATIVE",
    "contact.info.rep_val": "Kei-Yu Huang (Representative Director)",
    "contact.info.hq_label": "ADDRESS",
    "contact.info.hq_val": "#112 Neo Heights Isehara, 1-22-15 Sakuradai,\nIsehara-shi, Kanagawa 259-1132, Japan",
    "contact.info.license_label": "LICENSE",
    "contact.info.license_val": "Governor of Kanagawa (1) No. 32070",
    "contact.info.scope_label": "CORE BUSINESSES",
    "contact.info.scope_val": "Real Estate Brokerage, Leasing Management, Repurchase & Resale, Land Development, Bespoke Construction, Hospitality Operations",
    "contact.info.contact_label": "EMAIL",
    "contact.info.contact_val": "contact@yellowhouse.jp",
    "contact.info.hours_label": "OFFICE HOURS",
    "contact.info.hours_val": "Mon - Fri 09:00 - 18:00 (JST)\nOnline consultations available on weekends by appointment",
    "contact.quote": "“From acquisition, holding, management, development, and operations to resale, our hands-on experience empowers you to make informed decisions.”",

    // Currency
    "currency.label": "Currency",
    "currency.updated": "Exchange rate updated",
    "currency.updated_cached": "Exchange rate updated (cached offline)",
    "currency.unavailable": "Exchange rate temporarily unavailable — showing JPY only",
    "currency.approx": "Approx.",
    "currency.disclaimer": "USD amounts are approximate conversions based on the latest available exchange rate and may vary with market fluctuations.",
    "price.label": "PROPERTY PRICE"
  }
};

const LanguageContext = createContext<LanguageContextType>({
  lang: "zh",
  setLang: () => {},
  t: (key: string) => key
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Language>(() => {
    const saved = localStorage.getItem("yh_language");
    return saved === "en" ? "en" : "zh";
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem("yh_language", newLang);
  };

  const t = (key: string): string => {
    return translations[lang][key] || translations["zh"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
